/* Generated by Cython 3.1.3 */

#ifndef __PYX_HAVE__constants__Constants
#define __PYX_HAVE__constants__Constants

#include "Python.h"

#ifndef __PYX_HAVE_API__constants__Constants

#ifdef CYTHON_EXTERN_C
    #undef __PYX_EXTERN_C
    #define __PYX_EXTERN_C CYTHON_EXTERN_C
#elif defined(__PYX_EXTERN_C)
    #ifdef _MSC_VER
    #pragma message ("Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.")
    #else
    #warning Please do not define the '__PYX_EXTERN_C' macro externally. Use 'CYTHON_EXTERN_C' instead.
    #endif
#else
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *_ERR_MSG_SEQUENCE_UNSUPPORTED;
__PYX_EXTERN_C PyObject *_ERR_MSG_DIFF_DECIMAL_GROUP;
__PYX_EXTERN_C PyObject *_ERR_MSG_NO_CLOSING_BRACKET;
__PYX_EXTERN_C PyObject *_ERR_MSG_UNKNOWN_COMPONENT_SPECIFIER;
__PYX_EXTERN_C PyObject *_ERR_MSG_INVALID_NAME_MODIFIER;
__PYX_EXTERN_C PyObject *_ERR_MSG_TIMEZONE_FORMAT;
__PYX_EXTERN_C PyObject *_ERR_MSG_MISSING_FORMAT;
__PYX_EXTERN_C PyObject *_ERR_MSG_INVALID_OPTIONS_SINGLE_CHAR;
__PYX_EXTERN_C PyObject *_ERR_MSG_INVALID_OPTIONS_STRING;
__PYX_EXTERN_C PyObject *_SYMBOL_DECIMAL_SEPARATOR;
__PYX_EXTERN_C PyObject *_SYMBOL_GROUPING_SEPARATOR;
__PYX_EXTERN_C PyObject *_SYMBOL_INFINITY;
__PYX_EXTERN_C PyObject *_SYMBOL_MINUS_SIGN;
__PYX_EXTERN_C PyObject *_SYMBOL_NAN;
__PYX_EXTERN_C PyObject *_SYMBOL_PERCENT;
__PYX_EXTERN_C PyObject *_SYMBOL_PER_MILLE;
__PYX_EXTERN_C PyObject *_SYMBOL_ZERO_DIGIT;
__PYX_EXTERN_C PyObject *_SYMBOL_DIGIT;
__PYX_EXTERN_C PyObject *_SYMBOL_PATTERN_SEPARATOR;

#endif /* !__PYX_HAVE_API__constants__Constants */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

/* WARNING: Use PyImport_AppendInittab("Constants", PyInit_Constants) instead of calling PyInit_Constants directly from Python 3.5 */
PyMODINIT_FUNC PyInit_Constants(void);

#if PY_VERSION_HEX >= 0x03050000 && (defined(__GNUC__) || defined(__clang__) || defined(_MSC_VER) || (defined(__cplusplus) && __cplusplus >= 201402L))
#if defined(__cplusplus) && __cplusplus >= 201402L
[[deprecated("Use PyImport_AppendInittab(\"Constants\", PyInit_Constants) instead of calling PyInit_Constants directly.")]] inline
#elif defined(__GNUC__) || defined(__clang__)
__attribute__ ((__deprecated__("Use PyImport_AppendInittab(\"Constants\", PyInit_Constants) instead of calling PyInit_Constants directly."), __unused__)) __inline__
#elif defined(_MSC_VER)
__declspec(deprecated("Use PyImport_AppendInittab(\"Constants\", PyInit_Constants) instead of calling PyInit_Constants directly.")) __inline
#endif
static PyObject* __PYX_WARN_IF_PyInit_Constants_INIT_CALLED(PyObject* res) {
  return res;
}
#define PyInit_Constants() __PYX_WARN_IF_PyInit_Constants_INIT_CALLED(PyInit_Constants())
#endif

#endif /* !__PYX_HAVE__constants__Constants */
